---
    version: "2"
    services:
      postgres_db:
        image: postgres
        restart: always
        ports:
          - 5555:5432
        environment:
          - POSTGRES_HOST_AUTH_METHOD=trust
      